In [216]:
# subspace法のデバッグ用プログラム

In [217]:
import numpy as np
import numpy.linalg as LA

In [279]:
# 初期値設定
neig = 1
k = np.matrix([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,1]
])
m = np.matrix([[2,0,0],[0,2,0],[0,0,1]])
n = 3
ramda = np.zeros((neig,1))
x = np.random.rand(n,neig)
y = np.zeros((n,neig))
k_inv = np.linalg.inv(k)

In [280]:
print(y)
print(x)
print(ramda)

[[0.]
 [0.]
 [0.]]
[[0.42369564]
 [0.3826025 ]
 [0.06521568]]
[[0.]]


In [281]:
print(y)

[[0.]
 [0.]
 [0.]]


In [282]:
# 繰り返し処理:LA.eig利用
for i in range(50):
    print(i)
    ramold = ramda.copy()
    print(ramold)
    y = np.dot(np.dot(k_inv,m),x)
    kg = np.dot(np.dot(y.T, k), y)
    mg = np.dot(np.dot(y.T, m), y)
    mg = mg + np.eye(neig)*0.01
    mg_inv = np.linalg.inv(mg)
    w,v = LA.eig(np.dot(mg_inv, kg)) #w:固有値,v:固有ベクトル
    for i in range(neig):
        ramda[i][0] = w[i]
    print(ramda)
    print(ramold)
    p = v.T
    x = np.dot(y, p)
    for i in range(neig):
        max_val = 0
        for j in range(n):
            x_val = abs(x[j, i])
            if x_val > max_val:
                max_val = x_val
        for j in range(n):
            x[j, i] = x[j, i]/max_val
    han = (ramda - ramold)/ramda
    print(han)
    max_mod = 0
    for i in range(neig):
        if abs(han[i][0]) > max_mod:
            max_mod = abs(han[i][0])
    print(max_mod)
    if max_mod < 0.00002:
        break

0
[[0.]]
[[0.14123066]]
[[0.]]
[[1.]]
1.0
1
[[0.14123066]]
[[0.13409787]]
[[0.14123066]]
[[-0.05319094]]
0.05319094015412786
2
[[0.13409787]]
[[0.1339691]]
[[0.13409787]]
[[-0.00096115]]
0.0009611526554130051
3
[[0.1339691]]
[[0.13396665]]
[[0.1339691]]
[[-1.83149687e-05]]
1.831496866314077e-05


In [283]:
print(ramda)
print(x)

[[0.13396665]]
[[0.50032831]
 [0.8662219 ]
 [1.        ]]


In [284]:
print(x)

[[0.50032831]
 [0.8662219 ]
 [1.        ]]


In [285]:
print(1/ramda[0][0])

7.464544377669681


In [286]:
print(ramda)

[[0.13396665]]


In [87]:
# 繰り返し処理を一回だけ:ヤコビ法利用
ramold = ramda
y = np.dot(np.dot(k_inv,m),x)
kg = np.dot(np.dot(y.T, k), y)
mg = np.dot(np.dot(y.T, m), y)
mg_inv = np.linalg.inv(mg)
# ここを変える必要あり w,v = LA.eig(np.dot(mg_inv, kg)) #w:固有値,v:固有ベクトル